image: ashadicc/php-fpm

services:
  - mariadb:latest

variables:
  MYSQL_DATABASE: laravel
  MYSQL_ROOT_PASSWORD: password
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit