image: ashadicc/php-fpm

variables:
  MYSQL_DATABASE: laravel
  MYSQL_ROOT_PASSWORD: password

stages:
  - test

unit_test:
  stage: test
  services:
    - mariadb:latest
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit