version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mariadb
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: password

    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo apt update
            sudo docker-php-ext-configure pdo_mysql
            sudo docker-php-ext-install zip bcmath pdo_mysql
            sudo apt-get install default-mysql-client
      - run: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
            
      - run:
          name: Waiting mysql to be ready
          command: ./wait-for-it.sh 127.0.0.1:3306 --timeout=30

      - run:
          name: Running test
          environment:
            DB_HOST: 127.0.0.1
            DB_USERNAME: root
            DB_PASSWORD: password
            DB_PORT: 3306
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan migrate
            ./vendor/bin/phpunit

workflows:
  notify_deploy:
    jobs:
      - build
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - master
  version: 2
